---
title: "Services Map"
author: "Connor Flynn"
date: "4/24/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(here)
library(tidygeocoder)
library(mapview)
library(shiny)
library(leaflet)
```

Read in Data

```{r}
#facilities <- read_excel(here("National_Directory_MH_Facilities_2022.xlsx"))
```


Merge Columns

```{r}
# facilities <- facilities %>%
#   unite(whole_adress, c("street1", "city", "state", "zip"), sep = " ")
```

Geocode facilities (Takes 2.5 hours to run)

```{r}
# facilities <- facilities %>%
#   geocode(whole_adress, method = 'osm', lat = latitude , long = longitude)
```

Save geocoded facilities file

```{r}
#write_csv(facilities, here("geocoded_facilities.csv"))
```

Read in geocoded facilities file

```{r}
geocoded_facilities <- read_csv(here("geocoded_facilities.csv"))
```
```{r}
geocoded_facilities_filtered <- geocoded_facilities %>% 
  drop_na(longitude, latitude)
```


```{r}
mapview(geocoded_facilities_filtered, xcol = "longitude", ycol = "latitude", popup = "name1", crs = 4269, grid = FALSE, cex = 5)
```

```{r}
b <- breweries
```

For Quinn:

Use chatgpt to recode abbreviation into the full name

Can we make a leaflet map that you can filter by service offered 
- pivot_wider?

# Services offered bool seperation 

```{r}
service_list <- strsplit(as.character(geocoded_facilities_filtered$service_code_info), " \\* | ")
service_list

all_services <- unique(unlist(service_list))
all_services
```


```{r}
abbrev_dict <- c(
  "Substance use treatment" = "SA",
  "Mental health treatment" = "MH",
  "Treatment for co-occurring substance use plus either serious mental health illness in adults/serious emotional disturbance in children" = "SUMH",
  "Hospital inpatient/24-hour hospital inpatient" = "HI",
  "Outpatient" = "OP",
  "Partial hospitalization/day treatment" = "PHDT",
  "Residential/24-hour residential" = "RES",
  "Community mental health center" = "CMHC",
  "Certified Community Behavioral Health Clinic" = "CBHC",
  "Multi-setting mental health facility (e.g., non-hospital residential plus either outpatient and/or partial hospitalization/day treatment)" = "MSMH",
  "Outpatient mental health facility" = "OMH",
  "Other residential treatment facility" = "ORES",
  "Partial hospitalization/day treatment" = "PH",
  "Psychiatric hospital" = "PSY",
  "Residential treatment center (RTC) for adults" = "RTCA",
  "Residential treatment center (RTC) for children" = "RTCC",
  "Separate inpatient psychiatric unit of a general hospital" = "IPSY",
  "State hospital" = "SHP",
  "Veterans Affairs Medical Center or other VA healthcare facility" = "VAHC",
  "Chlorpromazine" = "CHLOR",
  "Droperidol" = "DROPE",
  "Fluphenazine" = "FLUPH",
  "Haloperidol" = "HALOP",
  "Loxapine" = "LOXAP",
  "Perphenazine" = "PERPH",
  "Pimozide" = "PIMOZ",
  "Prochlorperazine" = "PROCH",
  "Thiothixene" = "THIOT",
  "Thioridazine" = "THIOR",
  "Trifluoperazine" = "TRIFL",
  "Aripiprazole" = "ARIPI",
  "Asenapine" = "ASENA",
  "Brexpiprazole" = "BREXP",
  "Cariprazine" = "CARIP",
  "Clozapine" = "CLOZA",
  "Iloperidone" = "ILOPE",
  "Lurasidone" = "LURAS",
  "Olanzapine" = "OLANZ",
  "Olanzapine/Fluoxetine combination" = "OLANZF",
  "Paliperidone" = "PALIP",
  "Quetiapine" = "QUETI",
  "Risperidone" = "RISPE",
  "Ziprasidone" = "ZIPRA",
  "Nicotine replacement" = "NRT",
  "Non-nicotine smoking/tobacco cessation" = "NSC",
  "Antipsychotics used in treatment of SMI" = "ANTPYCH",
  "Activity therapy" = "AT",
  "Cognitive behavioral therapy" = "CBT",
  "Cognitive remediation therapy" = "CRT",
  "Couples/family therapy" = "CFT",
  "Dialectical behavior therapy" = "DBT",
  "Electroconvulsive therapy" = "ECT",
  "Eye Movement Desensitization and Reprocessing therapy" = "EMDR",
  "Group therapy" = "GT",
  "Integrated Mental and Substance Use Disorder treatment" = "IDD",
  "Individual psychotherapy" = "IPT",
  "Ketamine Infusion Therapy" = "KIT",
  "Transcranial Magnetic Stimulation" = "TMS",
  "Telemedicine/telehealth therapy" = "TELE",
  "Abnormal involuntary movement scale" = "AIM",
  "Crisis intervention team" = "CIT",
  "Psychiatric emergency onsite services" = "PEON",
  "Psychiatric emergency mobile/off-site services" = "PEOFF",
  "Psychiatric emergency walk-in services" = "WI",
  "Local, county, or community government" = "LCCG",
  "Department of Defense" = "DDF",
  "Indian Health Services" = "IH",
  "Private for-profit organization" = "PVTP",
  "Private non-profit organization" = "PVTN",
  "State government" = "STG",
  "Tribal government" = "TBG",
  "U.S. Department of Veterans Affairs" = "VAMC",
  "Federal Government" = "FED",
  "Federally Qualified Health Center" = "FQHC",
  "Mental health clinic or mental health center" = "MHC",
  "County or local government funds" = "CLF",
  "Community Mental Health Block Grants" = "CMHG",
  "Community Service Block Grants" = "CSBG",
  "Federal Grants" = "FG",
  "IHS/Tribal/Urban (ITU) funds" = "ITU",
  "Medicare" = "MC",
  "Medicaid" = "MD",
  "Federal military insurance (e.g., TRICARE)" = "MI",
  "Other State funds" = "OSF",
  "Private health insurance" = "PI",
  "Private or Community foundation" = "PCF",
  "State corrections or juvenile justice funds" = "SCJJ",
  "State education agency funds" = "SEF",
  "Cash or self-payment" = "SF",
  "State-financed health insurance plan other than Medicaid" = "SI",
  "State mental health agency (or equivalent) funds" = "SMHA",
  "State welfare or child and family services funds" = "SWFS",
  "U.S. Department of VA funds" = "VAF",
  "Payment assistance (check with facility for details)" = "PA",
  "Sliding fee scale (fee is based on income and other factors)" = "SS",
  "Young adults" = "TAY",
  "Seniors or older adults" = "SE",
  "Lesbian, gay, bisexual, transgender, or queer/questioning (LGBTQ)" = "GL",
  "Veterans" = "VET",
  "Active duty military" = "ADM",
  "Members of military families" = "MF",
  "Criminal justice (other than DUI/DWI)/Forensic clients" = "CJ",
  "Clients with co-occurring mental and substance use disorders" = "CO",
  "Clients with HIV or AIDS" = "HV",
  "Clients who have experienced intimate partner violence, domestic violence" = "DV",
  "Clients who have experienced trauma" = "TRMA",
  "Persons with traumatic brain injury (TBI)" = "TBI",
  "Persons with Alzheimer's or dementia" = "ALZ",
  "Persons with eating disorders" = "PED",
  "Persons experiencing first-episode psychosis" = "PEFP",
  "Persons with post-traumatic stress disorder (PTSD)" = "PTSD",
  "Children/adolescents with serious emotional disturbance (SED)" = "SED",
  "Persons 18 and older with serious mental illness (SMI)" = "SMI",
  "Screening for tobacco use" = "STU",
  "HIV testing" = "HIVT",
  "STD testing" = "STDT",
  "TB screening" = "TBS",
  "Metabolic syndrome monitoring" = "MST",
  "Testing for Hepatitis B (HBV)" = "HBT",
  "Testing for Hepatitis C (HCV)" = "HCT",
  "Laboratory testing" = "LABT",
  "Housing services" = "HS",
  "Mentoring/peer support" = "PEER",
  "Education and Counseling Services" = "TCC",
  "Smoking not permitted" = "SMON",
  "Smoking permitted without restriction" = "SMOP",
  "Smoking permitted in designated area" = "SMPD",
  "Children/adolescents" = "CHLD",
  "Seniors" = "SNR",
  "Young adults" = "YAD",
  "Spanish" = "SP",
  "Sign language services for the deaf and hard of hearing" = "AH",
  "American Indian or Alaska Native languages" = "NX",
  "Other languages (excluding Spanish)" = "FX",
  "Vaping not permitted" = "VAPN",
  "Vaping permitted without restriction" = "VAPP",
  "Vaping permitted in designated area" = "VPPD",
  "Assertive community treatment" = "ACT",
  "Assisted Outpatient Treatment" = "AOT",
  "Chronic disease/illness management" = "CDM",
  "Court-ordered outpatient treatment" = "COOT",
  "Diet and exercise counseling" = "DEC",
  "Family psychoeducation" = "FPSY",
  "Intensive case management" = "ICM",
  "Illness management and recovery" = "IMR",
  "Legal advocacy" = "LAD",
  "Psychosocial rehabilitation services" = "PRS",
  "Supported employment" = "SEMP",
  "Supported housing" = "SH",
  "Therapeutic foster care" = "TPC",
  "Vocational rehabilitation services" = "VRS",
  "Case management service" = "CM",
  "Integrated primary care services" = "IPC",
  "Suicide prevention services" = "SPS",
  "Education services" = "ES"
)

geocoded_facilities_filtered <- geocoded_facilities_filtered %>%
  mutate(service_code_info = recode(service_code_info, !!!abbrev_dict))
```

```{r}
binary_service <- data.frame(matrix(FALSE, nrow = nrow(geocoded_facilities_filtered), ncol = length(all_services)))
colnames(binary_service) <- all_services
```

```{r}
for (i in 1:nrow(geocoded_facilities_filtered)) {
  services_offered <- unlist(service_list[i])
  binary_service[i, services_offered] <- TRUE
}

services_facilities <- cbind(geocoded_facilities_filtered, binary_service)
services_facilities
```

```{r}
services_facilities <- subset(services_facilities, select = -c(service_code_info))
services_facilities
```



```{r}
ui <- fluidPage(
  titlePanel("Mental Health Facilities Map"),
  leafletOutput("map"),
  checkboxGroupInput("services", label = "Filter by Service:", choices = colnames(services_facilities)[12:ncol(services_facilities)], selected = character(0))
)


server <- function(input, output, session) {

  output$map <- renderLeaflet({
    leaflet() %>%
      addTiles() %>%
      addMarkers(data = services_facilities, ~longitude, ~latitude, popup = ~name1,
                 icon = leaflet::makeIcon(  
        iconUrl = "https://leafletjs.com/examples/custom-icons/leaf-green.png",     # icon edit not doing anything, maybe getting 
        iconWidth = 10,                                                             # rid of shadow would speed things up
        iconHeight = 60)
    )
  })
  

  observe({
    filtered_data <- services_facilities
    
    selected_services <- input$services
    
    for (service in colnames(services_facilities)[12:ncol(services_facilities)]) {
      if (service %in% selected_services) {
        filtered_data <- filtered_data[filtered_data[[service]], ]
      }
    }
    
    leafletProxy("map") %>%
      clearMarkers() %>%
      addMarkers(data = filtered_data, ~longitude, ~latitude, popup = ~name1)
  })
}


shinyApp(ui = ui, server = server)
```