---
title: "Filter Map"
author: "Connor Flynn"
date: "5/20/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(here)
library(tidygeocoder)
library(mapview)
library(shiny)
library(leaflet)
library(dplyr)
```

Read in Data

```{r}
#facilities <- read_excel(here("National_Directory_MH_Facilities_2022.xlsx"))
```


Merge Columns

```{r}
# facilities <- facilities %>%
#   unite(whole_adress, c("street1", "city", "state", "zip"), sep = " ")
```

Geocode facilities (Takes 2.5 hours to run)

```{r}
# facilities <- facilities %>%
#   geocode(whole_adress, method = 'osm', lat = latitude , long = longitude)
```

Save geocoded facilities file

```{r}
#write_csv(facilities, here("geocoded_facilities.csv"))
```

Read in geocoded facilities file

```{r}
geocoded_facilities <- read_csv(here("geocoded_facilities.csv"))
```


```{r}
geocoded_facilities_filtered <- geocoded_facilities %>% 
  drop_na(longitude, latitude)
```


```{r}
mapview(geocoded_facilities_filtered, xcol = "longitude", ycol = "latitude", popup = "name1", crs = 4269, grid = FALSE, cex = 5)
```



```{r}
geocoded_facilities_filtered <- geocoded_facilities_filtered %>% 
  select(name1, service_code_info, latitude, longitude)
```


```{r}
# Define categories and corresponding abbreviations
abbrev_dict <- list(
  "Treatment Types" = c("MH", "SUMH", "OP", "PHDT", "RES", "CMHC"),
  "Medications" = c("CHLOR", "FLUPH", "HALOP", "LOXAP", "PERPH", "PIMOZ",
                    "PROCH", "THIOT", "THIOR", "TRIFL", "ARIPI", "ASENA",
                    "BREXP", "CARIP", "CLOZA", "ILOPE", "LURAS", "OLANZ",
                    "OLANZF", "PALIP", "QUETI", "RISPE", "ZIPRA", "NRT",
                    "NSC", "ANTPYCH"),
  "Therapies and Treatment Approaches" = c("AT", "CBT", "CRT", "CFT", "DBT",
                                           "ECT", "EMDR", "GT", "IDD", "IPT",
                                           "KIT", "TMS", "TELE"),
  "Assessments and Scales" = c("AIM"),
  "Emergency and Crisis Services" = c("CIT", "PEON", "PEOFF", "WI"),
  "Government and Organization Types" = c("LCCG", "DDF", "IH", "PVTP", "PVTN",
                                          "STG", "TBG", "VAMC", "FED", "FQHC",
                                          "MHC"),
  "Funding Sources" = c("CLF", "CMHG", "CSBG", "FG", "ITU", "MC", "MD",
                        "MI", "OSF", "PI", "SCJJ", "SEF", "SF", "SMHA",
                        "SWFS", "VAF", "PA", "SS"),
  "Target Populations" = c("TAY", "SE", "GL", "VET", "ADM", "MF", "CJ", "CO",
                            "HV", "DV", "TRMA", "TBI", "ALZ", "PED", "PEFP",
                            "PTSD", "SED", "SMI"),
  "Health Screenings and Tests" = c("STU", "HIVT", "STDT", "TBS", "MST", "HBT",
                                    "HCT", "LABT"),
  "Support and Rehabilitation Services" = c("HS", "PEER", "TCC", "ACT", "AOT",
                                            "CDM", "COOT", "DEC", "FPSY", "ICM",
                                            "IMR", "LAD", "PRS", "SEMP", "SH",
                                            "TPC", "VRS", "CM", "IPC", "SPS"),
  "Smoking and Vaping Policies" = c("SMON", "SMOP", "SMPD", "VAPN", "VAPP",
                                     "VPPD"),
  "Language Services" = c("SP", "AH", "NX", "FX")
)

```


```{r}
# UI
ui <- fluidPage(
  selectInput("overall_category", "Select Overall Category:", choices = names(abbrev_dict)),
  selectInput("service", "Select Service:", choices = NULL),
  leafletOutput("map")
)

# Server
server <- function(input, output, session) {

  # Observe changes in overall_category and update service choices dynamically
  observeEvent(input$overall_category, {
    req(input$overall_category)
    updateSelectInput(session, "service", choices = abbrev_dict[[input$overall_category]])
  })

  # Reactive expression to filter data based on selected category and service
  filtered_data <- reactive({
    req(input$overall_category, input$service)
    
    services <- strsplit(geocoded_facilities_filtered$service_code_info, " \\* ")
    
    filtered <- geocoded_facilities_filtered[sapply(services, function(x) {
      any(grepl(input$service, x))
    }), ]
    
    return(filtered)
  })

  # Render leaflet map
  output$map <- renderLeaflet({
    leaflet() %>%
      addTiles()
  })

  # Observe changes in filtered_data and update map markers
  observe({
    data <- filtered_data()
    req(nrow(data) > 0)
    
    leafletProxy("map", data = data) %>%
      clearMarkers() %>%
      addCircleMarkers(
        lng = ~longitude, lat = ~latitude,
        popup = ~name1,
        radius = 5,
        color = "blue",
        stroke = FALSE,
        fillOpacity = 0.7
      ) %>%
      setView(
        lng = mean(data$longitude, na.rm = TRUE), 
        lat = mean(data$latitude, na.rm = TRUE), 
        zoom = 6
      )
  })
}

shinyApp(ui = ui, server = server)

```


test test test

